#!/bin/bash

# 🔧 Script de Configuración de Repositorio para CI/CD
# Configura las ramas y estructura para deployment continuo

set -e

# 🎨 COLORES
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() {
    echo -e "${GREEN}[$(date +'%H:%M:%S')] $1${NC}"
}

warn() {
    echo -e "${YELLOW}[$(date +'%H:%M:%S')] WARNING: $1${NC}"
}

error() {
    echo -e "${RED}[$(date +'%H:%M:%S')] ERROR: $1${NC}"
    exit 1
}

info() {
    echo -e "${BLUE}[$(date +'%H:%M:%S')] INFO: $1${NC}"
}

# 📂 PATHS
DEVELOPMENT_PATH="/var/www/cober360"
PRODUCTION_PATH="/var/www/cober360-produccion"

# 🔧 CONFIGURAR DESARROLLO (rama main)
setup_development() {
    log "🔧 Configurando entorno de desarrollo..."
    
    cd "$DEVELOPMENT_PATH"
    
    # Asegurar que estamos en main
    git checkout main 2>/dev/null || git checkout -b main
    
    # Limpiar cambios no commiteados si es necesario
    if [ "$(git status --porcelain)" ]; then
        warn "Hay cambios sin commitear en desarrollo"
        read -p "¿Commitear todos los cambios pendientes? (y/n): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            git add .
            git commit -m "feat: cambios pendientes antes de configurar CI/CD

- Configuración automática de CI/CD
- Sincronización de cambios pendientes
- Preparación para deployment automatizado

Generated by: setup_cicd.sh"
        else
            info "Guardando cambios en stash..."
            git stash push -m "Cambios pendientes - configuración CI/CD $(date)"
        fi
    fi
    
    # Push de main al repositorio
    git push origin main || warn "No se pudo hacer push a main"
    
    log "✅ Desarrollo configurado en rama 'main'"
}

# 🏭 CONFIGURAR PRODUCCIÓN (rama production)
setup_production() {
    log "🏭 Configurando entorno de producción..."
    
    cd "$PRODUCTION_PATH"
    
    # Crear y cambiar a rama production
    git checkout main 2>/dev/null || git checkout -b main
    
    # Limpiar cambios si es necesario
    if [ "$(git status --porcelain)" ]; then
        warn "Hay cambios sin commitear en producción"
        git add .
        git commit -m "prod: estado actual de producción

- Captura del estado de producción actual
- Preparación para rama production
- Configuración automática de CI/CD

Generated by: setup_cicd.sh"
    fi
    
    # Crear rama production desde el estado actual
    git checkout -b production 2>/dev/null || git checkout production
    
    # Push de production al repositorio
    git push origin production || git push --set-upstream origin production
    
    log "✅ Producción configurada en rama 'production'"
}

# 🔄 CREAR RAMA DEVELOP
setup_develop() {
    log "🔄 Configurando rama develop..."
    
    cd "$DEVELOPMENT_PATH"
    
    # Crear rama develop desde main
    git checkout main
    git checkout -b develop 2>/dev/null || git checkout develop
    git push origin develop || git push --set-upstream origin develop
    
    log "✅ Rama 'develop' creada y configurada"
}

# 📝 CREAR ARCHIVO DE CONFIGURACIÓN DE ENTORNO
create_env_files() {
    log "📝 Creando archivos de configuración..."
    
    # .env para desarrollo
    if [ ! -f "$DEVELOPMENT_PATH/backend/.env" ]; then
        cat > "$DEVELOPMENT_PATH/backend/.env" << 'EOF'
# 🔧 CONFIGURACIÓN DE DESARROLLO - Cober360
NODE_ENV=development
PORT=4000

# 🗄️ BASE DE DATOS
DB_HOST=localhost
DB_PORT=3306
DB_NAME=cober360_dev
DB_USER=root
DB_PASS=Tu_Password_Aqui

# 🔐 SEGURIDAD
JWT_SECRET=tu_jwt_secret_super_secreto_para_desarrollo
SESSION_SECRET=tu_session_secret_para_desarrollo

# 📧 EMAIL (desarrollo)
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_USER=desarrollo@cober.online
EMAIL_PASS=tu_email_password

# 🌍 URLS
FRONTEND_URL=http://localhost:5173
BACKEND_URL=http://localhost:4000

# 📱 WHATSAPP (desarrollo)
WHATSAPP_TOKEN=tu_whatsapp_token_dev
WHATSAPP_VERIFY_TOKEN=tu_verify_token_dev

# 🔍 LOGGING
LOG_LEVEL=debug
EOF
        log "✅ Archivo .env de desarrollo creado"
    fi
    
    # .env para producción
    if [ ! -f "$PRODUCTION_PATH/backend/.env" ]; then
        cat > "$PRODUCTION_PATH/backend/.env" << 'EOF'
# 🏭 CONFIGURACIÓN DE PRODUCCIÓN - Cober360
NODE_ENV=production
PORT=4000

# 🗄️ BASE DE DATOS
DB_HOST=localhost
DB_PORT=3306
DB_NAME=cober360
DB_USER=root
DB_PASS=Tu_Password_Aqui_Prod

# 🔐 SEGURIDAD (CAMBIAR EN PRODUCCIÓN)
JWT_SECRET=tu_jwt_secret_ultra_secreto_para_produccion
SESSION_SECRET=tu_session_secret_ultra_secreto_para_produccion

# 📧 EMAIL (producción)
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_USER=sistema@cober.online
EMAIL_PASS=tu_email_password_prod

# 🌍 URLS
FRONTEND_URL=https://360.cober.online
BACKEND_URL=https://api.cober.online

# 📱 WHATSAPP (producción)
WHATSAPP_TOKEN=tu_whatsapp_token_prod
WHATSAPP_VERIFY_TOKEN=tu_verify_token_prod

# 🔍 LOGGING
LOG_LEVEL=error
EOF
        log "✅ Archivo .env de producción creado"
    fi
}

# 📋 CONFIGURAR SCRIPTS DE PACKAGE.JSON
setup_npm_scripts() {
    log "📋 Configurando scripts de NPM..."
    
    # Backend scripts
    cd "$DEVELOPMENT_PATH/backend"
    
    # Verificar si package.json existe
    if [ -f "package.json" ]; then
        # Agregar scripts de testing y CI/CD si no existen
        npm pkg set scripts.test="jest --testTimeout=10000"
        npm pkg set scripts.test:watch="jest --watch"
        npm pkg set scripts.test:coverage="jest --coverage"
        npm pkg set scripts.test:security="npm audit --audit-level moderate"
        npm pkg set scripts.test:api="node scripts/test_api_endpoints.js"
        npm pkg set scripts.lint="eslint . --ext .js"
        npm pkg set scripts.lint:fix="eslint . --ext .js --fix"
        npm pkg set scripts.db:migrate="node scripts/migrate.js"
        npm pkg set scripts.db:seed="node scripts/seed.js"
        npm pkg set scripts.start:dev="nodemon server.js"
        npm pkg set scripts.start:prod="node server.js"
        npm pkg set scripts.build="echo 'Backend build completed'"
        
        log "✅ Scripts de backend configurados"
    fi
    
    # Frontend scripts
    cd "$DEVELOPMENT_PATH/frontend"
    
    if [ -f "package.json" ]; then
        npm pkg set scripts.test="vitest run"
        npm pkg set scripts.test:watch="vitest"
        npm pkg set scripts.test:coverage="vitest run --coverage"
        npm pkg set scripts.lint="eslint src --ext .js,.jsx,.ts,.tsx"
        npm pkg set scripts.lint:fix="eslint src --ext .js,.jsx,.ts,.tsx --fix"
        npm pkg set scripts.build:production="vite build --mode production"
        npm pkg set scripts.preview="vite preview"
        
        log "✅ Scripts de frontend configurados"
    fi
}

# 🐳 CREAR DOCKERFILE PARA DESARROLLO
create_dockerfile() {
    log "🐳 Creando Dockerfile para desarrollo..."
    
    cat > "$DEVELOPMENT_PATH/Dockerfile.dev" << 'EOF'
# 🐳 Dockerfile para Desarrollo - Cober360
FROM node:18-alpine

# 📂 Crear directorio de trabajo
WORKDIR /app

# 📦 Copiar package.json files
COPY backend/package*.json ./backend/
COPY frontend/package*.json ./frontend/

# 🔧 Instalar dependencias
RUN cd backend && npm ci
RUN cd frontend && npm ci

# 📁 Copiar código fuente
COPY . .

# 🏗️ Build frontend
RUN cd frontend && npm run build

# 🚀 Exponer puerto
EXPOSE 4000

# 🎯 Comando por defecto
CMD ["npm", "run", "start:dev"]
EOF

    log "✅ Dockerfile de desarrollo creado"
}

# 📊 CONFIGURAR MONITOREO
setup_monitoring() {
    log "📊 Configurando herramientas de monitoreo..."
    
    # Crear script de health check
    cat > "$DEVELOPMENT_PATH/scripts/health_check.sh" << 'EOF'
#!/bin/bash

# 🏥 Health Check Script para Cober360

API_URL="http://localhost:4000/health"
TIMEOUT=10

echo "🏥 Verificando salud del sistema..."

# Test API
if curl -f -s --max-time $TIMEOUT "$API_URL" > /dev/null; then
    echo "✅ API: OK"
else
    echo "❌ API: FAIL"
    exit 1
fi

# Test Database
if mysqladmin ping -h localhost --silent; then
    echo "✅ Database: OK"
else
    echo "❌ Database: FAIL"
    exit 1
fi

# Test PM2
if pm2 list | grep -q "online"; then
    echo "✅ PM2: OK"
else
    echo "❌ PM2: FAIL"
    exit 1
fi

echo "🎉 Sistema saludable"
EOF

    chmod +x "$DEVELOPMENT_PATH/scripts/health_check.sh"
    
    log "✅ Health check configurado"
}

# 📚 CREAR DOCUMENTACIÓN
create_documentation() {
    log "📚 Creando documentación de CI/CD..."
    
    cat > "$DEVELOPMENT_PATH/CI_CD_DOCUMENTATION.md" << 'EOF'
# 🚀 CI/CD Pipeline - Cober360

## 📋 Descripción General

Este documento describe el pipeline de CI/CD (Integración y Despliegue Continuo) implementado para Cober360.

## 🌿 Estructura de Ramas

- **`main`**: Rama principal de desarrollo (staging)
- **`develop`**: Rama de desarrollo activo
- **`production`**: Rama de producción

## 🔄 Flujo de Trabajo

### 1. Desarrollo
```bash
# Trabajar en rama develop
git checkout develop
git pull origin develop

# Hacer cambios y commits
git add .
git commit -m "feat: nueva funcionalidad"
git push origin develop
```

### 2. Staging/Testing
```bash
# Merge a main para testing
git checkout main
git merge develop
git push origin main
```

### 3. Producción
```bash
# Merge a production para deploy
git checkout production
git merge main
git push origin production
```

## 🤖 Automatización

### GitHub Actions
- **Testing**: Se ejecuta en push a `main` y `develop`
- **Build**: Se ejecuta en push a `main` y `production`
- **Deploy**: Se ejecuta en push a `production`

### Scripts Locales
```bash
# Deploy manual
./scripts/deploy.sh

# Rollback
./scripts/deploy.sh rollback

# Health check
./scripts/deploy.sh health
```

## 🏥 Monitoreo

### Health Checks
- API: `http://localhost:4000/health`
- Database: Verificación de conexión MySQL
- PM2: Estado de procesos

### Logs
- Deploy logs: `/var/log/deploy-cober360.log`
- Application logs: `backend/logs/`
- PM2 logs: `pm2 logs`

## 🔧 Configuración

### Variables de Entorno
- Desarrollo: `backend/.env`
- Producción: `backend/.env` (en servidor de producción)

### Dependencias
```bash
# Backend
cd backend && npm ci

# Frontend  
cd frontend && npm ci && npm run build
```

## 🚨 Troubleshooting

### Problemas Comunes

1. **Deploy falla**
   ```bash
   ./scripts/deploy.sh rollback
   ```

2. **Tests fallan**
   ```bash
   cd backend && npm test
   cd frontend && npm test
   ```

3. **API no responde**
   ```bash
   pm2 restart all
   ```

### Contacto
- DevOps Team: devops@cober.online
- Sistema de tickets: GitHub Issues

## 📊 Métricas

- **Deployment frequency**: Diario
- **Lead time**: < 1 hora
- **MTTR**: < 15 minutos
- **Change failure rate**: < 5%
EOF

    log "✅ Documentación creada"
}

# 🎯 FUNCIÓN PRINCIPAL
main() {
    log "🚀 Iniciando configuración de CI/CD para Cober360"
    
    # Verificar que los directorios existen
    if [ ! -d "$DEVELOPMENT_PATH" ]; then
        error "Directorio de desarrollo no encontrado: $DEVELOPMENT_PATH"
    fi
    
    if [ ! -d "$PRODUCTION_PATH" ]; then
        error "Directorio de producción no encontrado: $PRODUCTION_PATH"
    fi
    
    # Ejecutar configuración
    setup_development
    setup_production
    setup_develop
    create_env_files
    setup_npm_scripts
    create_dockerfile
    setup_monitoring
    create_documentation
    
    log "🎉 Configuración de CI/CD completada"
    
    echo ""
    echo "📋 PRÓXIMOS PASOS:"
    echo "1. Revisar y actualizar archivos .env con tus credenciales"
    echo "2. Configurar secretos en GitHub Actions"
    echo "3. Ejecutar primer deployment: ./scripts/deploy.sh"
    echo "4. Verificar health check: ./scripts/health_check.sh"
    echo ""
    echo "📚 Ver documentación completa en: CI_CD_DOCUMENTATION.md"
}

# 📋 AYUDA
show_help() {
    echo "🔧 Script de Configuración de CI/CD para Cober360"
    echo ""
    echo "Uso: $0 [OPCIÓN]"
    echo ""
    echo "Opciones:"
    echo "  setup      Configuración completa (por defecto)"
    echo "  dev        Solo configurar desarrollo"
    echo "  prod       Solo configurar producción"
    echo "  help       Mostrar esta ayuda"
    echo ""
}

# 🎯 MANEJO DE ARGUMENTOS
case "${1:-setup}" in
    "setup")
        main
        ;;
    "dev")
        setup_development
        setup_develop
        ;;
    "prod")
        setup_production
        ;;
    "help"|"-h"|"--help")
        show_help
        ;;
    *)
        error "Opción no válida: $1. Usa '$0 help' para ver las opciones disponibles."
        ;;
esac