/*
 * Íconos con los nombres de react-icons (Fa*) y react-bootstrap-icons,
 * implementados con lucide-react (el set de íconos de shadcn/ui).
 *
 *   import { FaWhatsapp, FaUser } from "@/lib/icons";
 *
 * Igual que las librerías anteriores, miden 1em por defecto (toman el
 * tamaño del texto) y aceptan `size`, `color`, `className`, `style`, `title`.
 * En código nuevo usá lucide-react directamente.
 */
import * as L from "lucide-react";

const make = (Icon, displayName) => {
  const Comp = ({ size = "1em", title, style, ...props }) => (
    <Icon
      size={size}
      aria-hidden={title ? undefined : true}
      aria-label={title}
      role={title ? "img" : undefined}
      style={{ verticalAlign: "-0.125em", flexShrink: 0, ...style }}
      {...props}
    />
  );
  Comp.displayName = displayName;
  return Comp;
};

const MAP = {
  // --- react-icons/fa ---
  FaAddressBook: L.BookUser,
  FaArrowDown: L.ArrowDown,
  FaArrowLeft: L.ArrowLeft,
  FaArrowRight: L.ArrowRight,
  FaArrowUp: L.ArrowUp,
  FaBalanceScale: L.Scale,
  FaBan: L.Ban,
  FaBars: L.Menu,
  FaBell: L.Bell,
  FaBook: L.BookOpen,
  FaBuilding: L.Building2,
  FaBullseye: L.Target,
  FaCalendarAlt: L.CalendarDays,
  FaCashRegister: L.Receipt,
  FaChalkboardTeacher: L.Presentation,
  FaChartBar: L.ChartColumn,
  FaChartLine: L.ChartLine,
  FaChartPie: L.ChartPie,
  FaCheck: L.Check,
  FaCheckCircle: L.CircleCheck,
  FaCheckDouble: L.CheckCheck,
  FaChevronDown: L.ChevronDown,
  FaChevronLeft: L.ChevronLeft,
  FaChevronRight: L.ChevronRight,
  FaChevronUp: L.ChevronUp,
  FaCircle: L.Circle,
  FaClipboard: L.Clipboard,
  FaClipboardList: L.ClipboardList,
  FaClock: L.Clock,
  FaClone: L.Copy,
  FaCloudUploadAlt: L.CloudUpload,
  FaCog: L.Settings,
  FaCoins: L.Coins,
  FaComment: L.MessageSquare,
  FaCommentDots: L.MessageSquareText,
  FaComments: L.MessagesSquare,
  FaCopy: L.Copy,
  FaCreditCard: L.CreditCard,
  FaDatabase: L.Database,
  FaDesktop: L.Monitor,
  FaDollarSign: L.DollarSign,
  FaDownload: L.Download,
  FaEdit: L.SquarePen,
  FaEgg: L.Egg,
  FaEllipsisV: L.EllipsisVertical,
  FaEnvelope: L.Mail,
  FaEquals: L.Equal,
  FaExchangeAlt: L.ArrowLeftRight,
  FaExclamationTriangle: L.TriangleAlert,
  FaExternalLinkAlt: L.ExternalLink,
  FaEye: L.Eye,
  FaEyeSlash: L.EyeOff,
  FaFile: L.File,
  FaFileAlt: L.FileText,
  FaFileContract: L.FileSignature,
  FaFileCsv: L.FileSpreadsheet,
  FaFileExcel: L.FileSpreadsheet,
  FaFileExport: L.FileOutput,
  FaFileImport: L.FileInput,
  FaFileInvoiceDollar: L.ReceiptText,
  FaFilePdf: L.FileText,
  FaFileUpload: L.FileUp,
  FaFilter: L.Filter,
  FaFireAlt: L.Flame,
  FaFlag: L.Flag,
  FaFlask: L.FlaskConical,
  FaGift: L.Gift,
  FaGlobe: L.Globe,
  FaHandshake: L.Handshake,
  FaHdd: L.HardDrive,
  FaHeart: L.Heart,
  FaHistory: L.History,
  FaHome: L.House,
  FaHospital: L.Hospital,
  FaHourglassHalf: L.Hourglass,
  FaIdBadge: L.IdCard,
  FaIdCard: L.IdCard,
  FaImage: L.Image,
  FaInfo: L.Info,
  FaInfoCircle: L.Info,
  FaList: L.List,
  FaLocationArrow: L.Navigation,
  FaLock: L.Lock,
  FaMapMarkerAlt: L.MapPin,
  FaMemory: L.MemoryStick,
  FaMicrochip: L.Cpu,
  FaMobile: L.Smartphone,
  FaMobileAlt: L.Smartphone,
  FaMoneyBillWave: L.Banknote,
  FaNetworkWired: L.Network,
  FaPaperPlane: L.Send,
  FaPaperclip: L.Paperclip,
  FaPause: L.Pause,
  FaPeopleCarry: L.Truck,
  FaPercentage: L.Percent,
  FaPhone: L.Phone,
  FaPills: L.Tablets,
  FaPlay: L.Play,
  FaPlus: L.Plus,
  FaQuestion: L.CircleHelp,
  FaQuestionCircle: L.CircleHelp,
  FaRecycle: L.Recycle,
  FaRedoAlt: L.RotateCw,
  FaRobot: L.Bot,
  FaSave: L.Save,
  FaSearch: L.Search,
  FaServer: L.Server,
  FaShieldAlt: L.Shield,
  FaSignOutAlt: L.LogOut,
  FaSignal: L.Signal,
  FaSort: L.ArrowUpDown,
  FaSortDown: L.ArrowDownWideNarrow,
  FaSortUp: L.ArrowUpNarrowWide,
  FaSpinner: L.LoaderCircle,
  FaStore: L.Store,
  FaSync: L.RefreshCw,
  FaSyncAlt: L.RefreshCw,
  FaTachometerAlt: L.Gauge,
  FaTag: L.Tag,
  FaThLarge: L.LayoutGrid,
  FaTimes: L.X,
  FaTimesCircle: L.CircleX,
  FaToggleOff: L.ToggleLeft,
  FaToggleOn: L.ToggleRight,
  FaTrash: L.Trash2,
  FaTrashAlt: L.Trash2,
  FaUpload: L.Upload,
  FaUser: L.User,
  FaUserCheck: L.UserCheck,
  FaUserCircle: L.CircleUser,
  FaUserFriends: L.Users,
  FaUserMd: L.Stethoscope,
  FaUserPlus: L.UserPlus,
  FaUserShield: L.ShieldUser,
  FaUserTag: L.Contact,
  FaUserTie: L.Briefcase,
  FaUserTimes: L.UserX,
  FaUsers: L.Users,
  FaVenusMars: L.VenusAndMars,
  FaWhatsapp: L.MessageCircle,
  FaWifi: L.Wifi,

  // --- react-bootstrap-icons ---
  Activity: L.Activity,
  ArrowClockwise: L.RotateCw,
  BodyText: L.TextQuote,
  Building: L.Building2,
  Calendar3: L.CalendarDays,
  CardImage: L.Image,
  CashCoin: L.HandCoins,
  CheckCircle: L.CircleCheck,
  CheckCircleFill: L.CircleCheck,
  CheckSquare: L.SquareCheck,
  Clipboard2PlusFill: L.ClipboardPlus,
  CloudUploadFill: L.CloudUpload,
  CreditCard: L.CreditCard,
  CreditCard2BackFill: L.CreditCard,
  Download: L.Download,
  Envelope: L.Mail,
  EnvelopeFill: L.Mail,
  ExclamationCircleFill: L.CircleAlert,
  ExclamationTriangleFill: L.TriangleAlert,
  Eye: L.Eye,
  FileEarmarkArrowUp: L.FileUp,
  FileEarmarkImageFill: L.FileImage,
  FileEarmarkPdfFill: L.FileText,
  FileEarmarkPlus: L.FilePlus,
  FileEarmarkText: L.FileText,
  FileText: L.FileText,
  Flag: L.Flag,
  Gift: L.Gift,
  Heart: L.Heart,
  Hospital: L.Hospital,
  InfoCircleFill: L.Info,
  Lungs: L.Wind,
  PencilSquare: L.SquarePen,
  PeopleFill: L.Users,
  Person: L.User,
  PersonCheckFill: L.UserCheck,
  PersonFill: L.User,
  PersonFillGear: L.UserCog,
  PersonPlus: L.UserPlus,
  PlusCircle: L.CirclePlus,
  Prescription: L.ClipboardPlus,
  Send: L.Send,
  ShieldCheck: L.ShieldCheck,
  ShieldFillCheck: L.ShieldCheck,
  Telephone: L.Phone,
  Trash3Fill: L.Trash2,
  Upload: L.Upload,
  Whatsapp: L.MessageCircle,
  XCircle: L.CircleX,

  // --- @mui/icons-material ---
  Assessment: L.ChartColumn,
  DateRange: L.CalendarRange,
  Group: L.Users,
  Today: L.CalendarDays,
  TrendingUp: L.TrendingUp,
};

const I = Object.fromEntries(Object.entries(MAP).map(([name, Icon]) => [name, make(Icon, name)]));

export const {
  FaAddressBook, FaArrowDown, FaArrowLeft, FaArrowRight, FaArrowUp, FaBalanceScale, FaBan, FaBars, FaBell, FaBook,
  FaBuilding, FaBullseye, FaCalendarAlt, FaCashRegister, FaChalkboardTeacher, FaChartBar, FaChartLine, FaChartPie,
  FaCheck, FaCheckCircle, FaCheckDouble, FaChevronDown, FaChevronLeft, FaChevronRight, FaChevronUp, FaCircle,
  FaClipboard, FaClipboardList, FaClock, FaClone, FaCloudUploadAlt, FaCog, FaCoins, FaComment, FaCommentDots,
  FaComments, FaCopy, FaCreditCard, FaDatabase, FaDesktop, FaDollarSign, FaDownload, FaEdit, FaEgg, FaEllipsisV,
  FaEnvelope, FaEquals, FaExchangeAlt, FaExclamationTriangle, FaExternalLinkAlt, FaEye, FaEyeSlash, FaFile,
  FaFileAlt, FaFileContract, FaFileCsv, FaFileExcel, FaFileExport, FaFileImport, FaFileInvoiceDollar, FaFilePdf,
  FaFileUpload, FaFilter, FaFireAlt, FaFlag, FaFlask, FaGift, FaGlobe, FaHandshake, FaHdd, FaHeart, FaHistory,
  FaHome, FaHospital, FaHourglassHalf, FaIdBadge, FaIdCard, FaImage, FaInfo, FaInfoCircle, FaList,
  FaLocationArrow, FaLock, FaMapMarkerAlt, FaMemory, FaMicrochip, FaMobile, FaMobileAlt, FaMoneyBillWave,
  FaNetworkWired, FaPaperPlane, FaPaperclip, FaPause, FaPeopleCarry, FaPercentage, FaPhone, FaPills, FaPlay,
  FaPlus, FaQuestion, FaQuestionCircle, FaRecycle, FaRedoAlt, FaRobot, FaSave, FaSearch, FaServer, FaShieldAlt,
  FaSignOutAlt, FaSignal, FaSort, FaSortDown, FaSortUp, FaSpinner, FaStore, FaSync, FaSyncAlt, FaTachometerAlt,
  FaTag, FaThLarge, FaTimes, FaTimesCircle, FaToggleOff, FaToggleOn, FaTrash, FaTrashAlt, FaUpload, FaUser,
  FaUserCheck, FaUserCircle, FaUserFriends, FaUserMd, FaUserPlus, FaUserShield, FaUserTag, FaUserTie,
  FaUserTimes, FaUsers, FaVenusMars, FaWhatsapp, FaWifi,
  Activity, ArrowClockwise, BodyText, Building, Calendar3, CardImage, CashCoin, CheckCircle, CheckCircleFill,
  CheckSquare, Clipboard2PlusFill, CloudUploadFill, CreditCard, CreditCard2BackFill, Download, Envelope,
  EnvelopeFill, ExclamationCircleFill, ExclamationTriangleFill, Eye, FileEarmarkArrowUp, FileEarmarkImageFill,
  FileEarmarkPdfFill, FileEarmarkPlus, FileEarmarkText, FileText, Flag, Gift, Heart, Hospital, InfoCircleFill,
  Lungs, PencilSquare, PeopleFill, Person, PersonCheckFill, PersonFill, PersonFillGear, PersonPlus, PlusCircle,
  Prescription, Send, ShieldCheck, ShieldFillCheck, Telephone, Trash3Fill, Upload, Whatsapp, XCircle,
  Assessment, DateRange, Group, Today, TrendingUp,
} = I;
